name: Firmware release workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    tags:
     - 'v*.*.*'
     
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout repository
        run: |
          ls
      - name: Install GNU Arm Embedded Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '6-2017-q2' # <-- The compiler release to use

      - name: Test ARM GCC
        run: |
          arm-none-eabi-gcc -v
          make
          
      - name: Set Date
        run: echo "action_date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV
             
      - name: Set env
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: See env
        run: echo "${{ env.RELEASE_VERSION }}"
         
      - name: Zipping artifacts for Discord      
        uses: vimtor/action-zip@v1
        with:
          files: build/intech_grid/
          dest: grid_uf2_${{ env.action_date }}.zip
          
      - name: Zipping artifacts for Github Release   
        uses: vimtor/action-zip@v1
        with:
          files: build/intech_grid/
          dest: grid_uf2_release.zip
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Grid Bootloader ${{ env.RELEASE_VERSION }} (${{ env.action_date }})
          files: grid_uf2_release.zip    
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
